### ISSUE TITLE
Cards with correct resolution get displayed way too large.

### ISSUE THREAD

**Issue by DrVecctor** [finol-digital/Card-Game-Simulator#148]
**Describe the bug**
I have card images at a resolution of 250 x 350 pixels and set the card size to 2.5 x 3.5 inches.
This corresponds to the 100 PPI described in the instructions.
Still, when importing them, the cards are displayed so large when "exploring cards" or "building decks" that the whole screen is taken up by just the upper half of a card.

**Comment by davidmfinol** [comment]
If you go to Global Settings and increase the setting for Resolution there, does that seem better to you?

To provide some context on what's happening, the PPI information is used only while playing a game.
It's used to help determine where things will be placed on the virtual tabletop, where the virtual tabletop defaults to 36 inches by 36 inches.
CGS can't know the size of your physical screen, and it instead just renders to a certain resolution depending on your platform. 
The default target resolution (if no information is known about the physical screen size or platform) is 1920 x 1080.
For that resolution, each card's height of 350 pixels takes up 1/3 of the total 1080. 
Since we need to display other beyond just the cards, that means you'll only get like 2.5 cards appearing vertically. 

Does that help? Or is there some other issue that I'm missing here?

**Comment by DrVecctor** [comment]
I have the resolution already set to way bigger than my screen actually supports, but setting it my screen resolution (1080) only enlarges the background image. The files I am loading are PNG and I can not tell if they have some "PPI" save inside the file. But the problem occurs when loading cards, not on the "table". But those are not the only problems. Loading a single card does not work, the load buttom just does not react. And when starting a game, there is no way to get a deck to appear on the table, it might just be a graphics issue....

**Comment by davidmfinol** [comment]
I do recommend setting the resolution for CGS to be higher than your screen's resolution.
On my laptop, I use the resolution of 3200 x 1800, even though my screen's resolution is also only 1080p.

Can you share a screenshot or video of the problem you're having? It sounds like I'm missing something, and maybe it will be easier for me to understand if I can visually see it.

**Comment by davidmfinol** [comment]
I found that there was an i18n issue, where CGS was failing to parse numbers based off radix, ie `2.5` vs `2,5` and `3.5` vs `3,5`

This issue should be fixed in v1.116.

**Comment by DrVecctor** [comment]
Yes, the cards appear in normal size now!
